#cloud-config

packages:
  - sudo # ensure sudo is available
  - auditd # kernel audit support
runcmd:
  - curl -L \
    -o /usr/local/bin/collector \
    https://github.com/Ramsey-B/collector/releases/download/v1.0.0/collector-linux-amd64

  - chmod +x /usr/local/bin/collector

  # Run it as a simple background service
  - nohup sudo /usr/local/bin/collector -interval 5s \
    > /var/log/collector.log 2>&1 &
