#cloud-config

packages:
  - sudo # ensure sudo is available
  - auditd # kernel audit support
runcmd:
  - arch=$(uname -m)
  - if [ "$arch" = "aarch64" ]; then bin=collector-arm64; else bin=collector-amd64; fi
  - curl -fSL -o /usr/local/bin/collector https://github.com/Ramsey-B/collector/releases/download/latest/$bin
  - chmod +x /usr/local/bin/collector
  - nohup /usr/local/bin/collector -interval 5s > /var/log/collector.log 2>&1 &
  - sleep 6
  - head -n 20 /var/log/collector.log
