packages:
  - sudo # ensure sudo is available
  - auditd # kernel audit support
runcmd:
  - arch=$(uname -m)
  - if [ "$arch" = "aarch64" ]; then bin=collector-arm64; else bin=collector-amd64; fi
  - curl -fSL -o /usr/local/bin/collector https://github.com/Ramsey-B/collector/releases/download/latest/$bin
  - chmod +x /usr/local/bin/collector

  - HOST_GW=$(ip route | awk '/default/ {print $3}')
  - nohup /usr/local/bin/collector -interval 5s -endpoint http://$HOST_GW:3000/api/v1.0/logs > /var/log/collector.log 2>&1 &
