packages:
  - sudo

runcmd:
  # Ensure apt is up-to-date
  - |
    apt-get update

  # Install the generic tools package
  - |
    apt-get install -y linux-tools-common

  # Install the kernel-specific tools
  - |
    apt-get install -y \
      linux-tools-$(uname -r) \
      linux-headers-$(uname -r)

  # Install eBPF build dependencies
  - |
    apt-get install -y \
      clang llvm \
      libelf-dev libbpf-dev \
      build-essential \
      iproute2

  # Verify installation
  - |
    echo "=== bpftool version ==="
    bpftool version || echo "bpftool not found"
    echo "=== clang version ==="
    clang --version | head -n1

  # Install collector
  - arch=$(uname -m)
  - if [ "$arch" = "aarch64" ]; then bin=collector-arm64; else bin=collector-amd64; fi
  - curl -fSL -o /usr/local/bin/collector https://github.com/Ramsey-B/collector/releases/download/latest/$bin
  - chmod +x /usr/local/bin/collector

  # Run collector
  - nohup /usr/local/bin/collector -interval 5s > /var/log/collector.log 2>&1 &
